import localFont from "next/font/local";
import HeaderComponent from './components/HeaderComponent/HeaderComponent'
import FooterComponent from './components/FooterComponent/FooterComponent'
import CartProvider from './contexts/cartContext/cartProvider'
import StyledRegistry from './registry';
import { GlobalStyle } from './globalStyles';

const mohave = localFont({
  src: "./fonts/Mohave-VariableFont_wght.ttf",
  variable: "--font-mohave",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mohave.variable}`}>
        <StyledRegistry>
          <GlobalStyle />
            <CartProvider>
              <HeaderComponent />
                {children}
              <FooterComponent />
            </CartProvider>
        </StyledRegistry>
      </body>
    </html>
  );
}
